
export default function Head() {
  return (
    <head>
      <title>MyTop - наш лучший топ</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin='anonymous'/>
      <link rel="stylesheet"  href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300;400;500;700&display=swap" />
    </head>
  );
}
